### PR TITLE
better parser & error handling

### LINKED ISSUE #8: Future plans for this language
What are the plans for the (near) future of the language?

Im currently working on a better parser & lexer and will update this issue with the new grammar

The current grammar is defined like this:
```
//  '*' means zero or more
//  '?' means zero or one

unit ::= expr*

expr ::= include
    | return
    | function
    | for
    | until
    | if
    | let
    | compare
    | array
    | closure
    | get
    | call
    | arithmetic
    | constant

include ::= 'include' id
return ::= 'return' expr
function ::= 'fn' id '(' (id (',' id)*)? ')' block
for ::= 'for' id 'in' expr block
until ::= 'until' expr block
if ::= 'if' expr block ('else' block)?
let ::= 'let' id '=' expr
compare ::= compare_valid cmp_operator compare_valid 
compare_valid ::= call | constant
array ::= '[' (expr (',' expr)*)? ']'
closure ::= '|' (id (',' id)*)? '|' block
get ::= id '[' [0-9]+ ']' 
call ::= id '('  '(' (expr (',' expr)*)? ')' 
arithmetic ::= additive_expr 
constant ::= string | integer | float | bool | id


additive_expr ::= multiplicative_expr (('+' | '-') additive_expr)?
multiplicative_expr ::= factor  (('*' | '/') multiplicative_expr)?
factor ::= constant | '(' expr ')' 

cmp_operator ::= '==' | '!=' | '<' | '>' | '<=' | '>='

block ::= '{' expr* '}'

//constants (with regex, just examples)
id ::= [a-zA-Z_][a-zA-Z0-9_]*
string ::= ".*"
integer ::= (-)? [0-9]+
float ::= (-)? [0-9]* \.  [0-9]* 
bool ::= 'true' | 'false'
```

The parser and lexer parts are currently happening at the same time. 
The Lexer has to run first, to turn everything into tokens, then apply these tokens to a grammar to build the ast.
Also the current grammar is just not working, see #4. (Properly explaining it, would take to long)

Also is it possible to just remove the copyright header for each file? Its not nessesary and might deter new contributors.

### PR DESCRIPTION
**Pull request by Plixo2**
I implemented a Tokenizer to convert the source text into a list of `TokenRecords`, then apply these with a updated parser. 

These parse Expressions get then converted to the runtime expression

This type of Tokenizer and Parser doesn't copy any strings, only points to where the token is stored, so it's pretty fast.
It's possible to switch to a custom Tokenizer and Parser to take full advantage of this in the future.

I used [nom_locate](https://crates.io/crates/nom_locate) for some error reporting with source code location. And  [codespan_reporting](https://crates.io/crates/codespan-reporting) for expected errors (user errors)

The tokenizer is still missing support for string interpolation, but that can be implemented later

### CODE REVIEW

File: mussel/src/main.rs [hunk 1]
```diff
@@ -55,12 +58,19 @@ fn main() -> Result<()> {
...
+    let file = file.as_str();
+    let program = input.as_str();
+    let input = LocatedSpan::new_extra(program, file);
+    let result = lexer::lex(input)?;
+    result.iter().for_each(|r| println!("{:?}", r));
+
+    let expressions = parser2::parser(&result).map_err(|e| e.create_report(file, program))?;
+
+    expressions.iter().for_each(|r| println!("{:?}", r));
+
```
Comment (Plixo2) [inline mussel/src/main.rs:71]: just print the tokens and the expression AST for now

File: mussel/src/lexer.rs [hunk 2]
```diff
@@ -0,0 +1,277 @@
...
+            if num_str.contains('.') {
+                Ok::<Token, ErrorTree<&'_ str>>(Token::Float)
+            } else {
+                Ok::<Token, ErrorTree<&'_ str>>(Token::Integer)
+            }
+        },
+    )(input)
+}
+
+/// Tests a string starting and ending with double quotes.
```
Comment (Plixo2) [inline mussel/src/lexer.rs:170]: missing string interpolation here

File: mussel/src/lexer.rs [hunk 3]
```diff
@@ -0,0 +1,277 @@
...
+            Token::Ignore
+        }),
+        map(delimited(tag("/*"), take_until("*/"), tag("*/")), |_| {
+            Token::Ignore
+        }),
+    ))(input)
+}
+
+/// Tests a number literal.
+/// Matches the following regex: [0-9]+(\.[0-9]+)?
```
Comment (Plixo2) [inline mussel/src/lexer.rs:156]: should use nom `double` for floats

File: mussel/src/lexer.rs [hunk 4]
```diff
@@ -0,0 +1,277 @@
...
+fn number(input: Span) -> IResult<Token> {
+    map_res(
+        recognize(pair(digit1, opt(pair(char('.'), digit1)))),
+        |num_str: Span| {
+            if num_str.contains('.') {
+                Ok::<Token, ErrorTree<&'_ str>>(Token::Float)
```
Comment (Plixo2) [inline mussel/src/lexer.rs:162]: should use nom `double` for floats

File: mussel/src/lexer.rs [hunk 5]
```diff
@@ -0,0 +1,277 @@
...
+                Ok::<Token, ErrorTree<&'_ str>>(Token::Integer)
+            }
+        },
+    )(input)
+}
+
+/// Tests a string starting and ending with double quotes.
+fn string_literal(input: Span) -> IResult<Token> {
+    let (input, _) = delimited(char('"'), take_while(|c| c != '"'), char('"'))(input)?;
+    Ok((input, Token::String))
```
Comment (Plixo2) [inline mussel/src/lexer.rs:173]: missing string interpolation here

**Comment by gianndev** [comment]
I took a look at the code and it looks like you're doing a great job. I especially like the fact that you're implementing a lexer using a new library: this definitely makes Mussel much more powerful and similar to "big" programming languages. At the moment the PR is set as draft and I can't wait to see the final version!

**Comment by Plixo2** [comment]
Thank you. I will complete it today or tomorrow

**Comment by gianndev** [comment]
I'm noticing that you're making a lot of major changes to the Mussel code, and since so far compared to version _0.1.0_, a lot of changes have already been made, if you agree I would release version _0.2.0_ with the current code.

In this way we can also publicise Mussel by saying that there has recently been a new release. .

**Comment by MatyasZsombor** [comment]
Does your current parser implementation support resynchronization? If not, I would be happy to implement it.

**Comment by Plixo2** [comment]
@gianndev no problem. Since my university has picked up again, i don't know when the parser will be ready. Would you consider creating new branch, after my next commit this evening, so others (@MatyasZsombor ) can work on it too?

The only things left are:

- converting from the expressions from the new parser to the Expressions needed for runtime. This should be relatively trivial. 

- improving float parsing. Replace the number tokenizer with the build-in nom `double`. 

- handle string interpolation: I never did this, but apparently you maintain a stack with the type of curly braces you encounter along with a state machine. Encountering a string would transition into the string state. When you encounter a opening brace, push a starting-interpolation-brace onto the stack and transition back to the normal mode. When you encounter a opening brace in normal mode, push a start-default token onto the stack. When encountering a closing brace, match the type of opening brace and when the top is a starting-interpolation-brace, transition back to the string state


@MatyasZsombor I didn't and I don't know how to do it properly in nom, so help would be appreciated

**Comment by gianndev** [comment]
> Would you consider creating new branch, after my next commit this evening, so others (@MatyasZsombor) can work on it too?

Do you mean that tonight you're going to send me a PR and that I should create a branch after accepting the changes in the branch `develop`? Because in this case I think @MatyasZsombor can just update the branch `develop` of its fork. 

Then of course if @MatyasZsombor has any problems just tell me.

**Comment by Plixo2** [comment]
Everything is working now, please review it

**Review by gianndev — CHANGES_REQUESTED** [review]
I tried to run some Mussel code but I get printed on the screen as output not only what the code requires but also other information that maybe are fine in the development phase, but are not suitable for production. Let me explain: I tried to run the _hello.mus_ code, which simply prints a "Hello, World!" on the screen, but instead of having only that text I got printed on the screen:

```
 Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.15s
     Running `target\debug\mussel.exe ../examples/hello.mus`
TokenRecord { token_type: Identifier, offset: 0, length: 7 }
TokenRecord { token_type: LParenthesis, offset: 7, length: 1 }
TokenRecord { token_type: String, offset: 8, length: 16 }
TokenRecord { token_type: RParenthesis, offset: 24, length: 1 }
Call { region: TokenRecord { token_type: LParenthesis, offset: 7, length: 1 }, left: Identifier(TokenRecord { token_type: Identifier, offset: 0, length: 7 }), args: [String(TokenRecord { token_type: String, offset: 8, length: 16 })] }
Hello, Mussel!
```

**I think it would be appropriate to avoid showing all this information on the screen in the terminal when you are trying to run simple code.**

As for the new error handling I am very happy that now they are finally shown with a real, clear and direct error message.

**Comment by Plixo2** [comment]
Yes, but you can remove that yourself. I have to focus on my university now.

Just remove the prints in the main file.

**Comment by gianndev** [comment]
Ok i perfectly understand you're busy now. I'll correct it by myself, and **thanks again for have made Mussel a really better language** 😁

**Review by gianndev — APPROVED** [review]
Everything is fine, thanks again for the effort in upgrading Mussel so much
